### ISSUE TITLE
Usage (in WebUI) 遇到提示Torch not compiled with CUDA enabled的错误，我已经按照要求安装了cuda12.3，请问这是什么导致的呢

### ISSUE THREAD

**Issue by piaotq** [modelscope/DiffSynth-Studio#114]
![image](https://github.com/user-attachments/assets/a812f888-859e-4b25-b3ad-7d009aae145b)

问题截图如下

![image](https://github.com/user-attachments/assets/2f781afe-6169-4151-a42f-e13e71e71ee0)

**Comment by piaotq** [comment]
可以关闭了，我退回到cuda12.1 重新部署可以了

**Comment by Artiprocher** [comment]
非常抱歉我们未能及时处理这个 issue，我们之后会在 windows 系统下做更多测试，尽量避免类似的情况
