### ISSUE TITLE
Does Diffutoon support training new custom style models?

### ISSUE THREAD

**Issue by Yuan-ManX** [modelscope/DiffSynth-Studio#126]

**Comment by Artiprocher** [comment]
Sorry. Diffutoon is an independent inference approach. It doesn't support training.

However, if you want to use new custom style models, you can train the models by yourself and load them in Diffutoon.

By the way, we updated the training framework recently. You can train new custom style models using [these scripts](https://github.com/modelscope/DiffSynth-Studio/tree/main/examples/train).
