### ISSUE TITLE
您好，在尝试streamlit时，会出现"已杀死"问题

### ISSUE THREAD

**Issue by thgpddl** [modelscope/DiffSynth-Studio#137]
我在streamlit中尝试stable_diffusion获得了效果
![image](https://github.com/user-attachments/assets/56afc236-cb4a-417d-8f0a-6135bc9d6b54)

但是当我使用HunyuanDiT，程序崩溃，如下图所示，请问可能是为什么？

![image](https://github.com/user-attachments/assets/b98b97c9-c643-4c73-9957-8c4e89df9a6f)

![image](https://github.com/user-attachments/assets/342772b0-1518-4c00-82e3-72c7635bd616)

**Comment by thgpddl** [comment]
已解决，多次尝试就好了

**Comment by thgpddl** [comment]
但是目前我生成的图片似乎和我绘制的没有太大关系，是如何设置哪里吗

**Comment by thgpddl** [comment]
还是有“被杀死”的情况

**Comment by Artiprocher** [comment]
请问可以提供详细的报错信息吗？

**Comment by JoshonSmith** [comment]
内存不足？

**Comment by thgpddl** [comment]
> 请问可以提供详细的报错信息吗？

没有详细的报错信息，就如上图的“以杀死”这个错误信息

**Comment by JoshonSmith** [comment]
> > 内存不足？
> 
> 不太清楚，因为没有详细的报错信息，但是我使用`nvidia-smi -l 1`命令监视显卡使用情况，运行时占用50%左右，没有用完

安装nvitop，可以实时监控显卡，并且有内存占用百分比

**Comment by thgpddl** [comment]
> > > 内存不足？
> > 
> > 
> > 不太清楚，因为没有详细的报错信息，但是我使用`nvidia-smi -l 1`命令监视显卡使用情况，运行时占用50%左右，没有用完
> 
> 安装nvitop，可以实时监控显卡，并且有内存占用百分比

谢谢，确实是RAM爆了，我的是32GB的RAM
