### ISSUE TITLE
无法通过kolors官方代码加载Diffsynth训练的lora权重

### ISSUE THREAD

**Issue by JoshonSmith** [modelscope/DiffSynth-Studio#143]

**Comment by JoshonSmith** [comment]
请问是否可以将epoch=0-step=500.ckpt 转为 pytorch_lora_weights.bin

**Comment by Artiprocher** [comment]
我们训练的 LoRA 权重只能通过我们自己的代码加载，请参考 `examples/train` 中给出的代码样例
