### ISSUE TITLE
SDXL和Kolors推理设置tiled=True

### ISSUE THREAD

**Issue by JoshonSmith** [modelscope/DiffSynth-Studio#148]
我最近基于老师们开源的Diffsynth，尝试减少推理时显存占用，
设置tiled=True后，显存会低一些，

请问会有什么负面影响吗？目前感知是会慢一些

**Comment by Artiprocher** [comment]
tiled=True 之后，内部会分块处理一张图，代价是画面整体的完整性会稍差
