### ISSUE TITLE
OSError: [WinError 126]

### ISSUE THREAD

**Issue by tontheonelove** [modelscope/DiffSynth-Studio#150]
i try run    

python -m streamlit run DiffSynth_Studio.py

Received error

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Ton\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by ArthurGalvincio** [comment]
hey! how did you solve that?
