### ISSUE TITLE
EhancedDDIM Reference

### ISSUE THREAD

**Issue by huiyang865** [modelscope/DiffSynth-Studio#213]
EhancedDDIM used in the code as schedule, is there any relevant information to introduce the principle of this algorithm? Does EhancedDDIM support inversion?

**Comment by Artiprocher** [comment]
This scheduler is implemented based on the original DDIM paper. It supports a special inversion (not the general DDIM Inversion). Please refer to the original paper of DiffSynth: https://arxiv.org/abs/2308.03463.
