### ISSUE TITLE
TOO MUCH ERRORS. 

### ISSUE THREAD

**Issue by Kimthanh27** [modelscope/DiffSynth-Studio#53]
File "D:\DiffSynth-Studio\venv\lib\site-packages\imageio\core\format.py", line 437, in get_data
    raise IndexError(index)
  can you pls help me. thank you !

**Comment by thgpddl** [comment]
I have the same problem, have you solved it please?

**Comment by thgpddl** [comment]
I have the same problem, have you solved it please?
